import bpy.types as _t

# pyright: reportIncompatibleMethodOverride=information

class Operator(_t.Operator):
    filepath: str
    layout: _t.UILayout
    def execute(self, context: _t.Context) -> set[str]:...
    def invoke(self, context: _t.Context, event: _t.Event)-> set[str]:...
    def draw(self, context: _t.Context) -> None:...
    def check(self, context: _t.Context) -> bool:...

class Panel(_t.Panel):
    layout: _t.UILayout
    def draw(self, context: _t.Context) -> None:...
    @classmethod
    def poll(cls, context: _t.Context) -> bool:...

class Menu(_t.Menu):
    layout: _t.UILayout
    def draw(self, context: _t.Context) -> None:...
    @classmethod
    def poll(cls, context: _t.Context) -> bool:...

class ShaderNodeCustomGroup(_t.ShaderNodeCustomGroup):
    def draw_buttons(self, context: _t.Context, layout: _t.UILayout):...

